---
# DEPLOYMENT FOR LOGIN DEV

apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-dev-dpl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login-dev
  template:
    metadata:
      name: login-dev
      labels:
        app: login-dev
    spec:
      containers:
        - name: login-dev
          image: yosiaagusta/login-dev
          ports:
            - containerPort: 10001
          volumeMounts:
            - name: config-svc
              mountPath: /config.json
              subPath: config.json
      volumes:
        - name: config-svc
          configMap:
            name: config-svc

---
# SERVICE FOR LOGIN DEV

apiVersion: v1
kind: Service
metadata:
  name: login-dev-svc
spec:
  selector:
    app:  login-dev
  ports:
    - port: 80
      targetPort: 10001


---
#  INGRESS FOR LOGIN DEV

kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: ingress-login-dev
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    # nginx.ingress.kubernetes.io/auth-url: "https://868c-118-99-110-136.ngrok.io/check"
    #    nginx.ingress.kubernetes.io/auth-url: /other
    # nginx.ingress.kubernetes.io/configuration-snippet: |
    #   auth_request_set $auth_status     $upstream_status;
    #   auth_request_set $token           $upstream_http_authorization;
    #   add_header       'Authorization'  $token;
    #   add_header       'Auth-Status'    $auth_status;
spec:
  rules:
    - host: b.yosiagusta.com
      http:
        paths:
          - path: /auth/([\w\d/-]+)$
            pathType: ImplementationSpecific
            backend:
              service:
                name: login-dev-svc
                port:
                  number: 80
